spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://43.204.210.161:27017/notificationdb} # Use the Docker MongoDB service name

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost} # Use Docker service name for RabbitMQ
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: guest
    password: guest

server:
  port: ${SERVER_PORT:8081} # Default to 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: ${MANAGEMENT_SERVER_PORT:9091} # Default to 9091

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    try-it-out-enabled: true
    filter: true
