version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ AMQP port
      - "15672:15672"  # RabbitMQ Management UI port

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  document-service:
    build:
      context: .
      dockerfile: document-service/Dockerfile
    container_name: document-service
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/documentdb
      - NOTIFICATION_SERVICE_URL=http://notification-service:8081/api/notifications
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=9090
    depends_on:
      - mongo

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8081:8081"
      - "9091:9091"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/notificationdb
      - SERVER_PORT=8081
      - MANAGEMENT_SERVER_PORT=9091
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo-data: