spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://127.0.0.1:27017/documentdb} # Default to provided URI
  cache:
    type: simple

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8081/v1/api/notifications} # Default to localhost URL

server:
  port: ${SERVER_PORT:8080} # Default to 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: ${MANAGEMENT_SERVER_PORT:9090} # Default to 9090
